{% set name = "mamonca" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mamonca-{{ version }}.tar.gz
  sha256: f238b958604f49934fbe72638864ed89dcc2e3909750c5de51dd47c28948ada8

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - python
    - cython
    - setuptools
    - pip
    - numpy
  run:
    - python
    - numpy

test:
  imports:
    - mamonca
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/samwaseda/mamonca
  summary: mamonca - interactive Magnetic Monte Carlo
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - samwaseda
    - jan-janssen
