{% set name = "mamonca" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mamonca-{{ version }}.tar.gz
  sha256: e01df7aeb53de31e701b9459bdfb3676bfe90cae1967f521371f211809959129

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 3
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - python
    - cython
    - pip
  run:
    - python
    - numpy

test:
  imports:
    - mc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/samwaseda/mamonca
  summary: mamonca - interactive Magnetic Monte Carlo
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - samwaseda
    - jan-janssen
