{% set name = "mamonca" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mamonca-{{ version }}.tar.gz
  sha256: c1c928a3542ffb65c233b517d4c4e9e84683f27b0548353792c594cb0cc4ea9d

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 2
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - python
    - cython
    - pip
  run:
    - python
    - numpy

test:
  imports:
    - mamonca
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/samwaseda/mamonca
  summary: mamonca - interactive Magnetic Monte Carlo
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - samwaseda
    - jan-janssen
